name: Build & publish to gh-pages

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "17.x"
            - name: Install dependencies
              run: npm ci
            - name: Log into git
              run: |
                  git config --global user.email "jameskimimk@gmail.com"
                  git config --global user.name "Linimik"
                  git remote set-url origin https://jameslinimk:${{ secrets.PASSWORD }}@github.com/jameslinimk/simple-game-maker.git
            - name: Toggle dev
              run: npm run devOff
            - name: Build docs
              run: npm run docs
            - name: Build website
              run: npm run build
            - name: Publish gh-pages
              run: npm run publish
