name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
      - name: Install dependencies
        run: npm ci
      - name: Log into git
        run: |
          git config --global user.email "jameskimimk@gmail.com"
          git config --global user.name "Linimik"
          git remote set-url https://jameslinimk:${{ secrets.PASSWORD }}@github.com/jameslinimk/simple-game-maker.git
      - run: npm run build
      - run: npm run publish
