name: Test current gh-page

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Run your tests
              run: npx playwright test
            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: playwright-results
                  path: test-results
